apiVersion: supabase.codanael.io/v1alpha1
kind: Supabase
metadata:
  name: main
  namespace: supabase-system
spec:
  database:
    instances: 1
    imageName: supabase/postgres:15.8.1.085
    storage:
      size: 10Gi
  gateway:
    gatewayClassName: envoy-gateway
    baseDomain: supabase.local
