apiVersion: supabase.codanael.io/v1alpha1
kind: SupabaseTenant
metadata:
  name: acme
  namespace: supabase-system
spec:
  tenantId: acme
  supabaseRef: main
  auth:
    siteURL: https://app.acme.com
    email:
      enabled: true
      autoconfirm: false
  storage:
    backend: file
    imageTransformation: true
  functions:
    verifyJWT: true
  resources: small
