apiVersion: supabase.codanael.io/v1alpha1
kind: Supabase
metadata:
  labels:
    app.kubernetes.io/name: supabase-operator
    app.kubernetes.io/managed-by: kustomize
  name: supabase-sample
spec:
  # TODO(user): Add fields here
